# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/accelshark/Documents/nbody2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/accelshark/Documents/nbody2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/accelshark/Documents/nbody2/CMakeFiles /home/accelshark/Documents/nbody2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/accelshark/Documents/nbody2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nbody2

# Build rule for target.
nbody2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nbody2
.PHONY : nbody2

# fast build rule for target.
nbody2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/build
.PHONY : nbody2/fast

nbody.o: nbody.cpp.o
.PHONY : nbody.o

# target to build an object file
nbody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody.cpp.o
.PHONY : nbody.cpp.o

nbody.i: nbody.cpp.i
.PHONY : nbody.i

# target to preprocess a source file
nbody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody.cpp.i
.PHONY : nbody.cpp.i

nbody.s: nbody.cpp.s
.PHONY : nbody.s

# target to generate assembly for a file
nbody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody.cpp.s
.PHONY : nbody.cpp.s

nbody_framebuffer.o: nbody_framebuffer.cpp.o
.PHONY : nbody_framebuffer.o

# target to build an object file
nbody_framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_framebuffer.cpp.o
.PHONY : nbody_framebuffer.cpp.o

nbody_framebuffer.i: nbody_framebuffer.cpp.i
.PHONY : nbody_framebuffer.i

# target to preprocess a source file
nbody_framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_framebuffer.cpp.i
.PHONY : nbody_framebuffer.cpp.i

nbody_framebuffer.s: nbody_framebuffer.cpp.s
.PHONY : nbody_framebuffer.s

# target to generate assembly for a file
nbody_framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_framebuffer.cpp.s
.PHONY : nbody_framebuffer.cpp.s

nbody_particle.o: nbody_particle.cpp.o
.PHONY : nbody_particle.o

# target to build an object file
nbody_particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_particle.cpp.o
.PHONY : nbody_particle.cpp.o

nbody_particle.i: nbody_particle.cpp.i
.PHONY : nbody_particle.i

# target to preprocess a source file
nbody_particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_particle.cpp.i
.PHONY : nbody_particle.cpp.i

nbody_particle.s: nbody_particle.cpp.s
.PHONY : nbody_particle.s

# target to generate assembly for a file
nbody_particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_particle.cpp.s
.PHONY : nbody_particle.cpp.s

nbody_particle_system.o: nbody_particle_system.cpp.o
.PHONY : nbody_particle_system.o

# target to build an object file
nbody_particle_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_particle_system.cpp.o
.PHONY : nbody_particle_system.cpp.o

nbody_particle_system.i: nbody_particle_system.cpp.i
.PHONY : nbody_particle_system.i

# target to preprocess a source file
nbody_particle_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_particle_system.cpp.i
.PHONY : nbody_particle_system.cpp.i

nbody_particle_system.s: nbody_particle_system.cpp.s
.PHONY : nbody_particle_system.s

# target to generate assembly for a file
nbody_particle_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_particle_system.cpp.s
.PHONY : nbody_particle_system.cpp.s

nbody_randomiser.o: nbody_randomiser.cpp.o
.PHONY : nbody_randomiser.o

# target to build an object file
nbody_randomiser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_randomiser.cpp.o
.PHONY : nbody_randomiser.cpp.o

nbody_randomiser.i: nbody_randomiser.cpp.i
.PHONY : nbody_randomiser.i

# target to preprocess a source file
nbody_randomiser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_randomiser.cpp.i
.PHONY : nbody_randomiser.cpp.i

nbody_randomiser.s: nbody_randomiser.cpp.s
.PHONY : nbody_randomiser.s

# target to generate assembly for a file
nbody_randomiser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nbody2.dir/build.make CMakeFiles/nbody2.dir/nbody_randomiser.cpp.s
.PHONY : nbody_randomiser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nbody2"
	@echo "... nbody.o"
	@echo "... nbody.i"
	@echo "... nbody.s"
	@echo "... nbody_framebuffer.o"
	@echo "... nbody_framebuffer.i"
	@echo "... nbody_framebuffer.s"
	@echo "... nbody_particle.o"
	@echo "... nbody_particle.i"
	@echo "... nbody_particle.s"
	@echo "... nbody_particle_system.o"
	@echo "... nbody_particle_system.i"
	@echo "... nbody_particle_system.s"
	@echo "... nbody_randomiser.o"
	@echo "... nbody_randomiser.i"
	@echo "... nbody_randomiser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

